-- insert users data
INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('A473634H', 'hengd', 'male', '13/11/1992', 'Singaporean');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('A617342E', 'sean', 'male', '20/08/1994', 'Singaporean');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('A937845H', 'sherry', 'female', '28/05/1995', 'Malaysian');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('A984739J', 'zac', 'male', '07/03/1998', 'Chinese');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('S189586A', 'hugh', 'male', '17/08/1948', 'New Zealand');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('S847328L', 'damith', 'male', '09/11/1975', 'Sri Lankan');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('S049389F', 'chris', 'female', '06/04/1990', 'Romanian');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('S048276G', 'david', 'male', '18/10/1986', 'American');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('S197094X', 'steve', 'male', '27/07/1963', 'Indonesian');

INSERT INTO LBACSYS.USERS (SID, NAME, GENDER, DOB, NATIONALITY)
VALUES ('S983748W', 'reza', 'male', '19/09/1968', 'Iranian');

-- insert addresses data
INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A473634H', 'mailing', '20 Heng Mui Keng Terrace');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A473634H', 'billing', '20 Heng Mui Keng Terrace');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A617342E', 'mailing', '357 Pasir Panjang Rd');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A617342E', 'billing', '357 Pasir Panjang Rd');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A937845H', 'mailing', '26 Prince Georges Park');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A937845H', 'billing', '26 Prince Georges Park');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A984739J', 'mailing', '125 College Ave East');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('A984739J', 'billing', '125 College Ave East');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S189586A', 'mailing', '521 Bukit Batok Street');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S189586A', 'billing', '521 Bukit Batok Street');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S847328L', 'mailing', 'No.2 Jurong East Street');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S847328L', 'billing', 'No.2 Jurong East Street');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S049389F', 'mailing', '1 Ah Moi Road');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S049389F', 'billing', '1 Ah Moi Road');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S048276G', 'mailing', '302 Tiong Bahru Rd');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S048276G', 'billing', '302 Tiong Bahru Rd');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S197094X', 'mailing', '257 Selegie Road');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S197094X', 'billing', '257 Selegie Road');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S983748W', 'mailing', '33 Jalan Minggu');

INSERT INTO LBACSYS.ADDRESSES (SID, TYPE, ADDRESS)
VALUES ('S983748W', 'billing', '33 Jalan Minggu');



COMMIT;
